### PR TITLE
[Listener] Update function of receiving sound waves and outputting check-in information

### PR DESCRIPTION
**Pull request by jopopcorn**
* Add logic to set the acoustic sensor of the receiver
* When you click the `get info button`, perform `controlReceiver()` if you have been granted permission.
* Update string resources to print check-in information in a format.
* `setUserInformation()`: Cut the string based on '/' and print out the phone number and region. The current time is printed according to the time the data was received.

+) Additional Discussions
It would be better to place the `setting button` in the MainActivity without placing them on the Speaker, ListenerFragment respectively. What do you think of it?

### CODE REVIEW

**Review by sujin9 — APPROVED** [review]
Yess I run this pr on my phone and check it works properly !
You really did great ;)

**Comment by sujin9** [comment]
And regarding the discussion, I want to make sure of this first.
The setting button on the SpeakerFragment is intended to update user's information.
Then what does the setting button on the ListenerFragment do?

**Comment by jopopcorn** [comment]
Umm.. In my opinion, I don't think the setting button is needed on the ListenerFragment.
Is there any element to set up in the listener?

**Comment by jopopcorn** [comment]
Oh I thought about it, I think we need a default setting to register store information!
If the default setting was not entered when the screen was switched to ListenerFragment, it would be good to register store information on the new screen (for example, SettingActivity). What do you think of this?

**Pull request merged**
